# Generated by Django 4.2.30 on 2026-05-01 16:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('trainee', 'Trainee'), ('ta', 'TA'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin'), ('interviewer', 'Interviewer')], max_length=20)),
                ('access_start', models.DateTimeField(blank=True, null=True)),
                ('access_end', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_datetime', models.DateTimeField()),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('locked', 'Locked for Interview'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='locked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.JSONField()),
                ('openings', models.IntegerField(default=1)),
                ('filled', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('filled', 'Filled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('techSkills', models.JSONField(default=list)),
                ('softSkills', models.JSONField(default=list)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('postedDate', models.DateField(auto_now_add=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True, help_text='Public jobs are visible to associates')),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_id', models.CharField(max_length=36)),
                ('job_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('userId', models.CharField(max_length=64, unique=True)),
                ('averageScore', models.FloatField(blank=True, null=True)),
                ('employeeId', models.CharField(blank=True, max_length=64, null=True)),
                ('isu', models.CharField(blank=True, max_length=255, null=True)),
                ('isMapped', models.BooleanField(default=False)),
                ('projectId', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('projectName', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraineeSelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_asked', models.PositiveIntegerField(default=0)),
                ('technical_percentage', models.PositiveSmallIntegerField(default=50)),
                ('theoretical_percentage', models.PositiveSmallIntegerField(default=50)),
                ('question_list', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interview_lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessment', to='apis.interviewlock')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('upskillCourses', models.JSONField(blank=True, null=True)),
                ('certificates', models.JSONField(blank=True, null=True)),
                ('batchRank', models.CharField(blank=True, max_length=32, null=True)),
                ('groupRank', models.CharField(blank=True, max_length=32, null=True)),
                ('dpi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userInfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='apis.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apis.managerchatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='interviewlock',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_locks', to='apis.job'),
        ),
        migrations.AddField(
            model_name='interviewlock',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewlock',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_locks', to='apis.profilerecord'),
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('questions_asked', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('attitude_rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('behaviour_notes', models.TextField(blank=True)),
                ('technical_skills_assessed', models.JSONField(default=list)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('upskill_needed', models.TextField(blank=True)),
                ('overall_comments', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected')], max_length=10)),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='apis.interviewlock')),
            ],
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('avgScore', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='apis.profilerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'courseName'], name='apis_weakne_profile_d3c95d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('avgScore', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='apis.profilerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'courseName'], name='apis_streng_profile_309bed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=255)),
                ('trainee_location', models.CharField(blank=True, max_length=255, null=True)),
                ('trainee_id', models.CharField(max_length=64)),
                ('job_id', models.IntegerField()),
                ('job_title', models.CharField(max_length=200)),
                ('skills_percentage', models.FloatField(default=0.0)),
                ('location_percentage', models.FloatField(default=0.0)),
                ('total_percentage', models.FloatField(default=0.0)),
                ('bucket', models.CharField(choices=[('PERFECT_MATCH', 'Perfect Match'), ('SKILLS_ONLY', 'Skills Only'), ('LOCATION_ONLY', 'Location Only'), ('NEARBY', 'Nearby'), ('NO_MATCH', 'No Match')], default='NO_MATCH', max_length=50)),
                ('distance', models.FloatField(default=9999.0)),
                ('matched_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='apis.job')),
                ('trainee_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='apis.profilerecord')),
            ],
            options={
                'ordering': ['-total_percentage'],
                'unique_together': {('job_ref', 'trainee_ref')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='interviewlock',
            unique_together={('trainee', 'job')},
        ),
    ]
