# Generated by Django 5.2.7 on 2025-12-31 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.JSONField()),
                ('openings', models.IntegerField(default=1)),
                ('filled', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('filled', 'Filled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('techSkills', models.JSONField(default=list)),
                ('softSkills', models.JSONField(default=list)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('postedDate', models.DateField(auto_now_add=True)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
