# Generated by Django 4.2.7 on 2026-05-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_job_bg_job_demand_id_job_isu_hsu_job_rmg_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='expiryDate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='softSkills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='techSkills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='project_name',
            field=models.CharField(default='', help_text='Project Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='', help_text='Skills - comma separated', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='bg',
            field=models.CharField(blank=True, help_text='BG', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='demand_id',
            field=models.CharField(default='', help_text='Demand ID', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='isu_hsu',
            field=models.CharField(blank=True, help_text='ISU/HSU', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(help_text='Location(s) - comma separated for multiple', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='openings',
            field=models.IntegerField(default=1, help_text='Number of openings'),
        ),
        migrations.AlterField(
            model_name='job',
            name='rmg_head',
            field=models.CharField(blank=True, help_text='RMG Head', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(blank=True, help_text='Role (Developer, Tech Support, etc)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='spoc_emp_id',
            field=models.CharField(blank=True, help_text='Project SPOC Emp ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='spoc_name',
            field=models.CharField(blank=True, help_text='Project SPOC Name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='stream',
            field=models.CharField(blank=True, help_text='Stream (Java, Python etc)', max_length=100, null=True),
        ),
    ]
