# Generated by Django 5.1.1 on 2026-01-08 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('userId', models.CharField(max_length=64)),
                ('averageScore', models.FloatField(blank=True, null=True)),
                ('employeeId', models.CharField(blank=True, max_length=64, null=True)),
                ('isu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('upskillCourses', models.JSONField(blank=True, null=True)),
                ('certificates', models.JSONField(blank=True, null=True)),
                ('batchRank', models.CharField(blank=True, max_length=32, null=True)),
                ('groupRank', models.CharField(blank=True, max_length=32, null=True)),
                ('dpi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userInfo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='apis.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('avgScore', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='apis.profilerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'courseName'], name='apis_streng_profile_309bed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('avgScore', models.FloatField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='apis.profilerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'courseName'], name='apis_weakne_profile_d3c95d_idx')],
            },
        ),
    ]
