# Generated by Django 4.2.7 on 2026-05-31 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_course_notifications_audit_matching_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.AddField(
            model_name='course',
            name='owners',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'course_owner'}, related_name='owned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='recommendation_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Review'), ('completed', 'Review Completed')], default='not_requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_jd', 'New JD Created'), ('matches_found', 'Matching Candidates Found'), ('candidate_selected', 'Candidate Selected'), ('candidate_rejected', 'Candidate Rejected'), ('opening_filled', 'Opening Filled'), ('interview_scheduled', 'Interview Scheduled'), ('feedback_submitted', 'Interview Feedback Submitted'), ('backup_restore', 'Backup/Restore'), ('recommendation_requested', 'Recommendation Requested')], max_length=40),
        ),
    ]
