# Generated by Django 5.1.1 on 2026-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='trainee_id',
            field=models.CharField(max_length=36),
        ),
    ]
