# Generated by Django 4.2.7 on 2026-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_course_owner_course_owners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='preferred_location_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preferred_location_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preferred_location_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
