# Generated by Django 5.1.1 on 2026-01-23 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_recommendation_trainee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isMapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='projectId',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='projectName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_name', models.CharField(max_length=255)),
                ('trainee_location', models.CharField(blank=True, max_length=255, null=True)),
                ('trainee_id', models.CharField(max_length=64)),
                ('job_id', models.IntegerField()),
                ('job_title', models.CharField(max_length=200)),
                ('skills_percentage', models.FloatField(default=0.0)),
                ('location_percentage', models.FloatField(default=0.0)),
                ('total_percentage', models.FloatField(default=0.0)),
                ('bucket', models.CharField(choices=[('PERFECT_MATCH', 'Perfect Match'), ('SKILLS_ONLY', 'Skills Only'), ('LOCATION_ONLY', 'Location Only'), ('NEARBY', 'Nearby'), ('NO_MATCH', 'No Match')], default='NO_MATCH', max_length=50)),
                ('distance', models.FloatField(default=9999.0)),
                ('matched_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='apis.job')),
                ('trainee_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='apis.profilerecord')),
            ],
            options={
                'ordering': ['-total_percentage'],
                'unique_together': {('job_ref', 'trainee_ref')},
            },
        ),
    ]
