# Generated by Django 4.2.7 on 2026-02-26 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_userinfo_ismapped_userinfo_projectid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public jobs are visible to associates'),
        ),
        migrations.CreateModel(
            name='InterviewLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_datetime', models.DateTimeField()),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('locked', 'Locked for Interview'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='locked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_locks', to='apis.job')),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_interviews', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_locks', to='apis.profilerecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('trainee', 'job')},
            },
        ),
    ]
