# Generated by Django 4.2.7 on 2026-08-23 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_userinfo_preferred_location_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rgs_id',
            field=models.CharField(blank=True, help_text='RGS ID - unique requirement identifier', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preferred_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preferred_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_jd', 'New JD Created'), ('matches_found', 'Matching Candidates Found'), ('candidate_selected', 'Candidate Selected'), ('candidate_rejected', 'Candidate Rejected'), ('opening_filled', 'Opening Filled'), ('interview_scheduled', 'Interview Scheduled'), ('feedback_submitted', 'Interview Feedback Submitted'), ('backup_restore', 'Backup/Restore'), ('recommendation_requested', 'Recommendation Requested'), ('consent_sent', 'Consent Sent'), ('consent_responded', 'Consent Responded')], max_length=40),
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='apis.job')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_consents', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='apis.profilerecord')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('trainee', 'job')},
            },
        ),
    ]
