# Generated by Django 4.2.7 on 2026-02-28 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_job_is_public_interviewlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewlock',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('ta', 'TA'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin'), ('interviewer', 'Interviewer')], max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('questions_asked', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('attitude_rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 (poor) to 5 (excellent)')),
                ('behaviour_notes', models.TextField(blank=True)),
                ('technical_skills_assessed', models.JSONField(default=list)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('upskill_needed', models.TextField(blank=True)),
                ('overall_comments', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected')], max_length=10)),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='apis.interviewlock')),
            ],
        ),
    ]
