# Generated by Django 4.2.7 on 2026-08-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_job_rgs_id_userinfo_preferred_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewlock',
            name='interview_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
