# Generated by Django 4.2.7 on 2026-09-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_interviewlock_interview_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shared_by',
            field=models.CharField(blank=True, choices=[('Direct BU', 'Direct BU'), ('RMG', 'RMG')], default='Direct BU', help_text='Shared By (Direct BU or RMG)', max_length=50, null=True),
        ),
    ]
