# Generated by Django 4.2.7 on 2026-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_userinfo_user_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerecord',
            name='batch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='attitude_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
