# Generated by Django 4.2.7 on 2026-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_profilerecord_batch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='batch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
