# Generated by Django 4.2.7 on 2026-04-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_managerchatsession_managerchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matched_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
