# Generated by Django 4.2.7 on 2026-04-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_match_matched_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeSelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_asked', models.PositiveIntegerField(default=0)),
                ('technical_percentage', models.PositiveSmallIntegerField(default=50)),
                ('theoretical_percentage', models.PositiveSmallIntegerField(default=50)),
                ('question_list', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interview_lock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_assessment', to='apis.interviewlock')),
            ],
        ),
    ]
