# Generated by Django 4.2.7 on 2026-04-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_traineeselfassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='access_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
