export const users = [
  {
    id: 2962,
    userId: 2962,
    name: "Chandini Saketi",
    username: "Chandini Saketi",
    email: "chandini.saketi@example.com",
    location: "pune",

    // Table fields
    skills: ["Python", "Java", "WebTech", "React.js", "Node.js"],
    projectsMatched: 6,
    totalProjects: 10,
    matchRate: 60,
    status: "Needs Training",
    joinedDate: "2024-02-10",
    currentProject: null,
    projectStatus: "open-pool",
    experience: "1.5 years",
    education: "B.Tech Computer Science",
    preferredLocation: "pune",

    // Modal fields
    strengths: ["BizSkills", "Behavior Skill", "Projects"],
    weakness: ["Python", "Java", "WebTech"],
    upskillCourses: [
      {
        id: 2,
        courseId: 5386,
        courseName: "Python E1 competency",
        url: "https://ievolveng.ultimatix.net/ievolve/competencydetails/5386",
        platform: "Ievolve",
      },
      {
        id: 11,
        courseId: 5835,
        courseName: "Python- Web Frameworks E1 competency",
        url: "https://ievolveng.ultimatix.net/ievolve/competencydetails/5835",
        platform: "Ievolve",
      },
      {
        id: 1,
        courseId: 3224,
        courseName: "Java E1 competency",
        url: "https://ievolveng.ultimatix.net/ievolve/competencydetails/3224",
        platform: "Ievolve",
      },
      {
        id: 15,
        courseId: 55957,
        courseName: "Node.js E1 competency",
        url: "https://ievolveng.ultimatix.net/ievolve/coursedetails/55957",
        platform: "Ievolve",
      },
      {
        id: 14,
        courseId: 5630,
        courseName: "React.js E1 competency",
        url: "https://ievolveng.ultimatix.net/ievolve/competencydetails/5630",
        platform: "Ievolve",
      },
    ],
    certificates: [
      {
        certificateId: 5,
        certificateName: "JAVA",
        provider: "UDEMY",
        acquiredDate: "2025-12-08",
        userId: 1,
      },
      {
        certificateId: 6,
        certificateName: "AWS Certified Solutions Architect – Associate",
        provider: "Amazon Web Services",
        acquiredDate: "2024-03-15",
        userId: 1,
      },
      {
        certificateId: 7,
        certificateName: "Google Professional Cloud Architect",
        provider: "Google Cloud",
        acquiredDate: "2023-11-05",
        userId: 1,
      },
      {
        certificateId: 8,
        certificateName: "Certified Kubernetes Administrator (CKA)",
        provider: "Cloud Native Computing Foundation",
        acquiredDate: "2025-01-10",
        userId: 1,
      },
      {
        certificateId: 9,
        certificateName: "Oracle Certified Professional, Java SE 11 Developer",
        provider: "Oracle",
        acquiredDate: "2022-09-30",
        userId: 1,
      },
    ],

    dpi: 1.95,
    isu: "NGM PS EBU & Delivery Governance, Risk & Security.",
    batchRank: "258/321",
    groupRank: "20/23",
    average: 36,
    role: "IGNITE TRAINEE",
  },
  {
    id: 101,
    userId: 101,
    name: "John Smith",
    email: "john.smith@example.com",
    location: "pune",
    skills: ["React", "JavaScript", "CSS", "Node.js"],
    projectsMatched: 8,
    totalProjects: 12,
    matchRate: 66.7,
    status: "Job Ready",
    joinedDate: "2024-01-15",
    currentProject: "E-commerce Platform",
    projectStatus: "approved",
    experience: "2 years",
    education: "B.Tech Computer Science",
    preferredLocation: "pune",
    strengths: ["Frontend", "Teamwork", "Problem Solving"],
    weakness: ["Java", "SQL"],
    upskillCourses: [],
    certificates: [],
    dpi: 2.2,
    isu: "NGM PS",
    batchRank: "120/321",
    groupRank: "10/23",
    average: 74,
    role: "IGNITE TRAINEE",
  },
  {
    id: 102,
    userId: 102,
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    location: "hyderabad",
    skills: ["React", "TypeScript", "UI/UX"],
    projectsMatched: 6,
    totalProjects: 10,
    matchRate: 60.0,
    status: "Needs Training",
    joinedDate: "2024-02-10",
    currentProject: null,
    projectStatus: "open-pool",
    experience: "1.5 years",
    education: "B.Des Graphic Design",
    preferredLocation: "hyderabad",
    strengths: ["UI/UX", "Visualization"],
    weakness: ["Node.js", "Databases"],
    upskillCourses: [],
    certificates: [],
    dpi: 1.8,
    isu: "NGM PS",
    batchRank: "240/321",
    groupRank: "18/23",
    average: 62,
    role: "IGNITE TRAINEE",
  },
  {
    id: 103,
    userId: 103,
    name: "Alex Johnson",
    email: "alex.j@example.com",
    location: "chennai",
    skills: ["Java", "Spring Boot", "MySQL"],
    projectsMatched: 10,
    totalProjects: 12,
    matchRate: 83.3,
    status: "Job Ready",
    joinedDate: "2024-01-20",
    currentProject: "Banking App",
    projectStatus: "approved",
    experience: "3 years",
    education: "M.Tech Computer Science",
    preferredLocation: "chennai",
    strengths: ["Backend", "DB Design"],
    weakness: ["Frontend CSS"],
    upskillCourses: [],
    certificates: [],
    dpi: 2.4,
    isu: "NGM PS",
    batchRank: "90/321",
    groupRank: "8/23",
    average: 86,
    role: "IGNITE TRAINEE",
  },
  {
    id: 104,
    userId: 104,
    name: "Priya Sharma",
    email: "priya.s@example.com",
    location: "pune",
    skills: ["Python", "Data Science", "ML"],
    projectsMatched: 4,
    totalProjects: 8,
    matchRate: 50.0,
    status: "Not Ready",
    joinedDate: "2024-02-05",
    currentProject: null,
    projectStatus: null,
    experience: "1 year",
    education: "B.Sc Data Science",
    preferredLocation: "pune",
    strengths: ["Statistics"],
    weakness: ["JavaScript", "React"],
    upskillCourses: [],
    certificates: [],
    dpi: 1.5,
    isu: "NGM PS",
    batchRank: "280/321",
    groupRank: "21/23",
    average: 55,
    role: "IGNITE TRAINEE",
  },
];

export const rec = [
    {
      id: 1,
      traineeId: 101,
      traineeName: "John Smith",
      traineeEmail: "john.smith@example.com",
      projectId: 1,
      projectName: "E-commerce Platform",
      recommendedBy: "TA - Dr. James Wilson",
      recommendationDate: "2024-02-15",
      status: "pending",
      matchScore: 94,
      skillsMatch: ["React", "JavaScript", "CSS"],
      locationMatch: "pune",
      reason: "Exceptional performance in React projects and excellent team collaboration skills",
      taComments: "John consistently demonstrates strong problem-solving abilities and has shown great initiative in previous projects.",
      priority: "high"
    },
    {
      id: 2,
      traineeId: 102,
      traineeName: "Emma Wilson",
      traineeEmail: "emma.wilson@example.com",
      projectId: 2,
      projectName: "Data Analytics Dashboard",
      recommendedBy: "TA - Dr. Sarah Chen",
      recommendationDate: "2024-02-14",
      status: "pending",
      matchScore: 88,
      skillsMatch: ["React", "TypeScript", "UI/UX"],
      locationMatch: "hyderabad",
      reason: "Strong UI/UX skills and experience with data visualization libraries",
      taComments: "Emma has a keen eye for design and has previously worked on similar dashboard projects.",
      priority: "medium"
    },
    {
      id: 3,
      traineeId: 103,
      traineeName: "Alex Johnson",
      traineeEmail: "alex.j@example.com",
      projectId: 3,
      projectName: "Mobile Banking App",
      recommendedBy: "TA - Prof. Robert Brown",
      recommendationDate: "2024-02-13",
      status: "approved",
      matchScore: 92,
      skillsMatch: ["JavaScript", "CSS", "Security"],
      locationMatch: "pune",
      reason: "Strong background in security and financial applications",
      taComments: "Mike has completed advanced security courses and has relevant banking domain knowledge.",
      priority: "high"
    },
    {
      id: 4,
      traineeId: 104,
      traineeName: "Priya Sharma",
      traineeEmail: "priya.s@example.com",
      projectId: 1,
      projectName: "E-commerce Platform",
      recommendedBy: "TA - Dr. James Wilson",
      recommendationDate: "2024-02-12",
      status: "rejected",
      matchScore: 85,
      skillsMatch: ["React", "JavaScript"],
      locationMatch: "pune",
      reason: "Skills gap in backend technologies required for the project",
      taComments: "Sarah is strong in frontend but needs more experience with Node.js and databases.",
      priority: "low"
    }
  ]

